/** Code auto-generated by cOde 0.4.1 **/
#include <R.h> 
 #include <math.h> 

static double parms[8];
static double forc[0];
static double cons[0];
static double range[2];

#define nGridpoints 500 
#define nSplines 0 
#define precision 1e-05 

#define k1 parms[0] 
 #define A parms[1] 
 #define k2 parms[2] 
 #define B parms[3] 
 #define k3 parms[4] 
 #define k4 parms[5] 
 #define y0_0 parms[6] 
 #define y1_0 parms[7] 
#define tmin range[0]
#define tmax range[1]


void brusselator_initmod(void (* odeparms)(int *, double *)) {
	 int N=8;
	 odeparms(&N, parms);
}

void brusselator_initforc(void (* odeforcs)(int *, double *)) {
	 int N=0;
	 odeforcs(&N, forc);
}

/** Derivatives (ODE system) **/
void brusselator_derivs (int *n, double *t, double *y, double *ydot, double *RPAR, int *IPAR) {

	 double time = *t;

	 ydot[0] = k1*A-k2*B*y[0]+k3*pow(y[0],2.0)*y[1]-k4*y[0];
 	 ydot[1] = k2*B*y[0]-k3*pow(y[0],2.0)*y[1];

}

